version: 2
publish: &publish
  working_directory: ~/my-app
  docker:
    - image: circleci/node:10.4.1
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: npm install

    - run:
        name: Test with jest
        command: npm run-script test

jobs:
  test_jest:
    <<: *publish

workflows:
  version: 2
  my_app:
    jobs:
      - test_jest:
          filters:
            branches:
              only: master
